from atomixlevels import atomix_levels
from stoneagelevels import stoneage_levels
from sokobanparser import parse_sokoban_levels

levels = [
	{
		"n": 1.1,
		"num_enemies": 5,
		"theme": "classic",
		"music": "a_new_path",
		"random_maze": True,
		"char_health": 100,
	},
	{
		"n": 1.2,
		"num_enemies": 0,
		"theme": "modern1",
		"music": "inspire",
		"time_limit": 30,
		"spiral_maze": True,
		"char_health": None,
		"has_finish": True,
	},
	{
		"n": 1.3,
		"num_enemies": 5,
		"theme": "classic",
		"music": "playful_sparrow",
		"random_maze": True,
		"four_rooms": True,
		"char_health": 200,
	},
	{
		"n": 1.4,
		"num_enemies": 20,
		"theme": "classic",
		"music": "valiant_warriors",
		"time_limit": 60,
		"char_health": 250,
		"bg_image": "bg/stonehenge.jpg",
		"cloud_mode": True,
	},
	{
		"n": 2.1,
		"num_enemies": 5,
		"theme": "classic",
		"music": "a_new_path",
		"random_maze": True,
		"char_health": 100,
		"gate_puzzle": {
			"num_gates": 2,
			"num_plates": 2,
		},
	},
	{
		"n": 2.2,
		"num_enemies": 5,
		"theme": "ancient2",
		"music": "the_last_kingdom",
		"random_maze": True,
		"char_health": 100,
		"gate_puzzle": {
			"num_gates": 4,
			"num_plates": 4,
			"all_gates_to_open": True,
		},
	},
	{
		"n": 2.3,
		"num_enemies": 5,
		"theme": "modern1",
		"music": "playful_sparrow",
		"spiral_maze": True,
		"char_health": 100,
		"cloud_mode": True,
		"gate_puzzle": {
			"num_gates": 6,
			"num_plates": 4,
		},
	},
	{
		"n": 2.4,
		"num_enemies": 5,
		"theme": "moss",
		"music": "forest_walk",
		"random_maze": True,
		"char_health": 100,
		"gate_puzzle": {
			"num_gates": 5,
			"num_plates": 5,
		},
	},
	{
		"n": 2.5,
		"num_enemies": 3,
		"theme": "minecraft",
		"music": "superepic_short",
		"random_maze": True,
		"char_health": 170,
		'four_rooms': True,
		"gate_puzzle": {
			"num_gates": (2, 3),
			"num_plates": range(2, 4),
		},
	},
	{
		"n": 2.6,
		"num_enemies": 5,
		"theme": "minecraft",
		"music": "film",
		"random_maze": True,
		"char_health": 100,
		"gate_puzzle": {
			"use_traps": True,
			"num_gates": 6,
			"num_plates": 3,
			"num_plates_to_press": 4,
		},
	},
	{
		"n": 3.01,
		"map_file": "switchbox/001.map",
		"title": "SwitchBox - level 1",
		"name": "Push and Open",
		"goal": "Push barrels into plates to open path",
		"num_enemies": 0,
		"theme": "classic",
		"music": "stoneage/02_bone_and_stone",
		"switchbox_puzzle": True
	},
	{
		"n": 3.02,
		"map_file": "switchbox/002.map",
		"title": "SwitchBox - level 2",
		"name": "Phase and Open",
		"goal": "Push and phase in barrels to open path",
		"num_enemies": 0,
		"theme": "modern1",
		"music": "stoneage/02_bone_and_stone",
		"switchbox_puzzle": True
	},
	{
		"n": 3.03,
		"map_file": "switchbox/003.map",
		"title": "SwitchBox - level 3",
		"name": "Swap and Open",
		"goal": "Push, phase in and swap barrels to open path",
		"num_enemies": 0,
		"theme": "ancient2",
		"music": "stoneage/02_bone_and_stone",
		"switchbox_puzzle": True
	},
	{
		"n": 3.04,
		"map_file": "switchbox/004.map",
		"title": "SwitchBox - level 4",
		"name": "Think and Open",
		"goal": "Think, push and phase in barrels to open path",
		"num_enemies": 0,
		"theme": "default",
		"music": "stoneage/02_bone_and_stone",
		"switchbox_puzzle": True
	},
	{
		"n": 3.1,
		"theme": "classic",
		"music": "stoneage/08_the_golden_valley.mp3",
		"char_power": 40,
		"hero_puzzle": True,
	},
	{
		"n": 3.2,
		"theme": "default",
		"music": "stoneage/08_the_golden_valley.mp3",
		"char_power": 40,
		"hero_puzzle": {
			"size": (7, 7),
			"strict_floors": True,
		},
	},
	{
		"n": 3.3,
		"theme": "moss",
		"music": "stoneage/08_the_golden_valley.mp3",
		"char_power": 40,
		"four_rooms": True,
		"hero_puzzle": True,
	},
	{
		"n": 3.91,
		"num_enemies": 0,
		"theme": "modern1",
		"music": "adventures",
		"four_rooms": True,
		"char_health": None,
		"color_puzzle": {
			"num_values": 2,
		},
	},
	{
		"n": 3.92,
		"num_enemies": 5,
		"theme": "modern1",
		"music": "valiant_warriors",
		"time_limit": 60,
		"char_health": 100,
		"color_puzzle": {
			"num_values": 4,
			"size": (9, 9),
		},
	},
	{
		"n": 3.93,
		"num_enemies": 5,
		"theme": "modern1",
		"music": "adventures",
		"time_limit": 120,
		"char_health": 100,
		"color_puzzle": {
			"num_values": 6,
			"size": (11, 11),
		},
	},
	{
		"n": 4.1,
		"bg_image": "bg/starry-sky.webp",
		"theme": "classic",
		"music": "breath",
		"char_health": 100,
		"four_rooms": True,
		"num_enemies": 0,
		"char_health": None,
		"allow_barrel_pull": True,
		"barrel_puzzle": {
			"num_barrels": range(3, 6),
			"use_ng": True,
		},
	},
	{
		"n": 4.2,
		"num_enemies": 5,
		"theme": "default",
		"music": "the_last_kingdom",
		"char_health": 100,
		"barrel_puzzle": {
			"size": (5, 5),
			"num_barrels": 5,
			"use_ng": True,
		},
	},
	{
		"n": 4.3,
		"theme": "moss",
		"music": "adventures",
		"num_enemies": 0,
		"char_health": None,
		"barrel_puzzle": {
			"num_barrels": 7,
			"use_ng": True,
		},
	},
	{
		"n": 4.4,
		"theme": "stoneage1",
		"music": "stoneage/03_plastic_age",
		"num_enemies": 0,
		"char_health": None,
		"barrel_puzzle": {
			"size": (9, 9),
			"num_barrels": 16,
		},
	},
	{
		"n": 4.5,
		"bg_image": "bg/starry-sky.webp",
		"theme": "stoneage5",
		"music": "stoneage/06_no_choice_left",
		"time_limit": 72,
		"char_health": 100,
		"nine_rooms": True,
		"num_enemies": 0,
		"char_health": None,
		"allow_barrel_pull": True,
		"barrel_puzzle": {
			"num_barrels": 2,
			"use_ng": True,
		},
	},
	{
		"n": 5.01,
		"name": "Minotaur Puzzle - autogenerated 7x7",
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "modern1",
		"music": "surface",
		"minotaur_puzzle": {
			"size": (7, 7),
		},
	},
	{
		"n": 5.02,
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "moss",
		"music": "surface",
		"minotaur_puzzle": {
			"size": (11, 11),
		},
	},
	{
		"n": 5.021,
		"goal": "finish-minotaur-puzzle",
		"map_file": "minotaur/001.map",
		"num_enemies": 0,
		"theme": "moss",
		"music": "surface",
		"minotaur_puzzle": True,
	},
	{
		"n": 5.022,
		"goal": "finish-minotaur-puzzle",
		"map_file": "minotaur/002.map",
		"num_enemies": 0,
		"theme": "moss",
		"music": "surface",
		"minotaur_puzzle": True,
	},
	{
		"n": 5.03,
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "minecraft",
		"music": "surface",
		"four_rooms": True,
		"minotaur_puzzle": {
		},
	},
	{
		"n": 5.04,
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "classic",
		"music": "surface",
		"nine_rooms": True,
		"minotaur_puzzle": {
			"allow_partially_trivial": True,
		},
	},
	{
		"n": 5.05,
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "ancient2",
		"music": "surface",
		"minotaur_puzzle": {
			"num_moves": 2,
			"size": (7, 5),
		},
	},
	{
		"n": 5.06,
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "modern2",
		"music": "surface",
		"minotaur_puzzle": {
			"num_moves": 3,
			"size": (7, 7),
		},
	},
	{
		"n": 5.07,
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "classic",
		"music": "surface",
		"four_rooms": True,
		"minotaur_puzzle": {
			"num_moves": 3,
		},
	},
	{
		"n": 5.08,
		"goal": "finish-minotaur-puzzle",
		"num_enemies": 0,
		"theme": "default",
		"music": "surface",
		"nine_rooms": True,
		"minotaur_puzzle": {
			"num_moves": 1,
			"allow_partially_trivial": True,
		},
	},
	{
		"n": 5.1,
		"num_enemies": 3,
		"theme": "ancient1",
		"music": "breath",
		"random_maze": True,
		"char_health": 100,
		"lock_puzzle": {
			"min_locks": 2,
			"max_locks": 3,
		},
	},
	{
		"n": 5.2,
		"num_enemies": 5,
		"theme": "ancient1",
		"music": "breath",
		"random_maze": True,
		"char_health": 100,
		"lock_puzzle": {
			"min_locks": 3,
			"max_locks": 5,
		},
	},
	{
		"n": 5.3,
		"theme": "ancient1",
		"music": "breath",
		"random_maze": True,
		"enemy_key_drop": True,
		"char_health": 150,
		"lock_puzzle": {
			"min_locks": 5,
			"max_locks": 7,
		},
	},
	{
		"n": 6.1,
		"theme": "modern1",
		"music": "epic_cinematic_trailer",
		"num_enemies": 0,
		"char_health": None,
		"memory_puzzle": {
			"size": (5, 3),
			"reveal_time": 10,
		},
	},
	{
		"n": 6.2,
		"theme": "stoneage1",
		"music": "stoneage/08_the_golden_valley",
		"has_start": True,
		"has_finish": True,
		"num_enemies": 0,
		"char_health": None,
		"memory_puzzle": {
			"size": (3, 4),
		},
	},
	{
		"n": 6.3,
		"theme": "classic",
		"music": "epic_cinematic_trailer",
		"four_rooms": True,
		"num_enemies": 2,
		"char_health": 100,
		"memory_puzzle": {
		},
	},
	{
		"n": 6.4,
		"theme": "ancient1",
		"music": "warfare",
		"nine_rooms": True,
		"time_limit": 150,
		"num_enemies": 0,
		"char_health": None,
		"memory_puzzle": {
			"size": (3, 3),
			"reveal_time": 8,
		},
	},
	{
		"n": 6.5,
		"theme": "moss",
		"music": "forest_walk",
		"num_enemies": 0,
		"time_limit": 300,
		"char_health": None,
		"goal": "solve-memory-puzzle-revealed",
		"memory_puzzle": {
			"is_revealed": True,
		},
	},
	{
		"n": 7.1,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"num_enemies": 0,
		"char_health": None,
		"goal": "solve-fifteen-puzzle",
		"fifteen_puzzle": {
			"size": (3, 2),
		},
	},
	{
		"n": 7.2,
		"theme": "moss",
		"music": "forest_walk",
		"nine_rooms": True,
		"num_enemies": 0,
		"char_health": None,
		"goal": "solve-fifteen-puzzle",
		"fifteen_puzzle": {
		},
	},
	{
		"n": 7.3,
		"theme": "stoneage1",
		"music": "film",
		"four_rooms": True,
		"num_enemies": 0,
		"char_health": None,
		"goal": "solve-fifteen-puzzle",
		"fifteen_puzzle": {
			"size": (4, 4),
		},
	},
	{
		"n": 7.4,
		"theme": "stoneage2",
		"music": "stoneage/08_the_golden_valley.mp3",
		"num_enemies": 15,
		"char_health": 200,
		"has_start": True,
		"has_finish": True,
		"goal": "solve-fifteen-puzzle",
		"fifteen_puzzle": {
			"size": (7, 7),
		},
	},
	{
		"n": 8.1,
		"theme": "default",
		"music": "forest_walk",
		"bg_image": "pictures/danik-lion-motocycle.jpg",
		"bg_image_crop": True,
		"num_enemies": 0,
		"char_health": None,
		"goal": "solve-rotatepic-puzzle",
		"rotatepic_puzzle": {
			"size": (8, 8),
		},
	},
	{
		"n": 8.2,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"has_start": True,
		"has_finish": True,
		"num_enemies": 10,
		"char_health": 150,
		"goal": "solve-rotatepic-puzzle",
		"rotatepic_puzzle": {
			"size": (7, 7),
			"image": "pictures/danik-lion-irisha-square.jpg",
		},
	},
	{
		"n": 8.3,
		"theme": "default",
		"music": "forest_walk",
		"num_enemies": 0,
		"char_health": None,
		"goal": "solve-rotatepic-puzzle",
		"rotatepic_puzzle": {
			"image": "pictures/danik-lego-tiger.jpg",
			"image_crop": True,
		},
	},
	{
		"n": 8.4,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"bg_image": "pictures/danik-lion-irisha-cafe.jpg",
#		"bg_image_crop": True,
		"num_enemies": 0,
		"char_health": None,
		"goal": "solve-rotatepic-puzzle",
		"rotatepic_puzzle": {
			"size": (9, 9),
		},
	},
	{
		"n": 9.1,
		"theme": "default",
		"music": "stoneage/01_stardust_falling",
		"num_enemies": 0,
		"char_health": None,
		"portal_puzzle": {
			"num_portals_per_hall": 2,
		},
	},
	{
		"n": 9.2,
		"theme": "stoneage2",
		"music": "stoneage/08_the_golden_valley.mp3",
		"has_start": True,
		"has_finish": True,
		"num_enemies": 5,
		"char_health": 100,
		"portal_puzzle": {
			"num_portals_per_hall": 3,
		},
	},
	{
		"n": 9.3,
		"theme": "moss",
		"music": "forest_walk",
		"num_enemies": 10,
		"char_health": 150,
		"portal_puzzle": {
		},
	},
	{
		"n": 10.1,
		"theme": "stoneage1",
		"bg_image": "bg/chemistry-1.webp",
		"music": "playful_sparrow.mp3",
		"goal": "{compose-bonus-molecule-with} 9 {atoms-word}",
		"num_enemies": 0,
		"char_health": None,
		"four_rooms": True,
		"atomix_puzzle": {
			"bonus_mode": 9,
		},
	},
	{
		"n": 10.2,
		"theme": "default",
		"bg_image": "bg/chemistry-2.webp",
		"music": "film.mp3",
		"goal": "compose-molecule",
		"num_enemies": 0,
		"char_health": None,
		"atomix_puzzle": {
			"molecule": "ethanol",
		},
	},
	{
		"n": 10.3,
		"theme": "moss",
		"bg_image": "bg/chemistry-2.webp",
		"music": "forest_walk",
		"goal": "{compose-bonus-molecule-with} 6 {atoms-word}",
		"num_enemies": 0,
		"char_health": None,
		"nine_rooms": True,
		"atomix_puzzle": {
			"bonus_mode": 6,
		},
	},
	{
		"n": 10.4,
		"theme": "stoneage2",
		"bg_image": "bg/chemistry-1.webp",
		"music": "epic_cinematic_trailer.mp3",
		"goal": "{compose-bonus-molecule-with} 15-16 {atoms-word}",
		"num_enemies": 0,
		"char_health": None,
		"atomix_puzzle": {
			"bonus_mode": (15, 16),
		},
	},
	{
		"n": 10.5,
		"theme": "modern1",
		"bg_image": "bg/chemistry-2.webp",
		"music": "adventures.mp3",
		"goal": "compose-molecule",
		"num_enemies": 0,
		"char_health": None,
		"atomix_puzzle": {
		},
	},
	{
		"n": 11.1,
		"map_size": (20, 11),
		"theme": "stoneage1",
		"music": "stoneage/01_stardust_falling",
		"bg_image": "bg/remains_of_a_threat.jpg",
		"num_enemies": 0,
		"char_health": None,
		"stoneage_puzzle": {
		},
	},
	*stoneage_levels,
	{
		"n": 1.0,
		"theme": "stoneage1",
		"music": "stoneage/08_the_golden_valley.mp3",
		"char_health": 40,
		"trivial_puzzle": True,
	},
	*atomix_levels,
	*parse_sokoban_levels(30, 'Thinking-Rabbit-Original-Plus-Extra.txt'),
	*parse_sokoban_levels(31, 'DrFogh-Original-1.txt'),
	*parse_sokoban_levels(32, 'DrFogh-Original-2.txt'),
	*parse_sokoban_levels(33, 'DrFogh-Original-3.txt'),
	*parse_sokoban_levels(41, 'dh1.txt'),
	*parse_sokoban_levels(42, 'dh2.txt'),
	*parse_sokoban_levels(43, 'microban.txt'),
	*parse_sokoban_levels(44, 'microcosmos.txt'),
	*parse_sokoban_levels(45, 'minicosmos.txt'),
	*parse_sokoban_levels(46, 'nabokosmos.txt'),
	*parse_sokoban_levels(47, 'picokosmos.txt'),
	*parse_sokoban_levels(48, 'sasquatch1.txt'),
	*parse_sokoban_levels(49, 'sasquatch2.txt'),
	*parse_sokoban_levels(50, 'sasquatch3.txt'),
	*parse_sokoban_levels(51, 'sasquatch4.txt'),
	*parse_sokoban_levels(52, 'sasquatch5.txt'),
	*parse_sokoban_levels(53, 'sokogen.txt'),
	*parse_sokoban_levels(54, 'yoshio.txt'),
]
