collections = [
	{
		"id": "tutorial",
		"name": "Tutorial levels",
		"n": 1.1,
		"icon": 'skeleton.png',
	},
	{
		"id": "gate",
		"name": "GatePuzzle levels",
		"n": 2.1,
		"icon": 'default/gate0.png',
	},
	{
		"id": "switchbox",
		"name": "SwitchBoxPuzzle levels",
		"n": 3.01,
		"icon": 'ancient2/gate0.png',
	},
	{
		"id": "hero",
		"name": "HeroPuzzle levels",
		"n": 3.1,
		"icon": 'default/might.png',
	},
	{
		"id": "color",
		"name": "ColorPuzzle levels",
		"n": 3.91,
		"icon": 'classic/plate.png',
	},
	{
		"id": "barrel",
		"name": "BarrelPuzzle levels",
		"n": 4.1,
		"icon": 'default/barrel.png',
	},
	{
		"id": "minotaur",
		"name": "MinotaurPuzzle levels",
		"n": 5.01,
		"icon": 'minotaur.png',
	},
	{
		"id": "lock",
		"name": "LockPuzzle levels",
		"n": 5.1,
		"icon": 'default/lock1.png',
	},
	{
		"id": "memory",
		"name": "MemoryPuzzle levels",
		"n": 6.1,
		"icon": 'modern2/cloud.png',
	},
	{
		"id": "fifteen",
		"name": "FifteenPuzzle levels",
		"n": 7.1,
		"icon": 'classic/beamcl.png',
	},
	{
		"id": "rotatepic",
		"name": "RotatePicPuzzle levels",
		"n": 8.1,
		"icon": 'classic/car.png',
	},
	{
		"id": "portal",
		"name": "PortalPuzzle levels",
		"n": 9.1,
		"icon": 'default/portal.png',
	},
	{
		"id": "atomix",
		"name": "Atomix levels",
		"n": 10.1,
		"icon": 'default/sphere-gray.png',
	},
	{
		"id": "stoneage",
		"name": "StoneAge levels",
		"n": 15.001,
		"icon": 'dinosaur.png',
	},
	{
		"id": "sokoban/original",
		"name": "Sokoban - Thinking Rabbit original + extra levels",
		"n": 30.001,
		"icon": 'ancient2/barrel.png',
	},
	{
		"id": "sokoban/assorted",
		"name": "Sokoban - Assorted collection levels",
		"n": 31.001,
		"icon": 'minecraft/barrel.png',
	},
	{
		"id": "sokoban/micro",
		"name": "Sokoban - Micro collection levels",
		"n": 43.001,
		"icon": 'modern1/barrel.png',
	},
]
