#!/usr/bin/python

import os
import sys
import numpy

sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/..')
from constants import *
from grid import grid
from test import TestSuite
from debug import debug
from teestream import stdout_redirected_to
from sokobanparser import is_sokoban_map, convert_and_pad_map_lines
from sokobansolver import *

sok_trivial_h1 = (
	'#####',
	'#@$.#',
	'#####',
)

sok_trivial_h2 = (
	' ### ',
	'#.$@#',
	' ### ',
)

sok_trivial_h3 = (
	'#####',
	'# @$.#',
	' #####',
)

sok_trivial_h4 = (
	' #####',
	'#.$ @#',
	'#####',
)

sok_trivial_v1 = (
	' #',
	'#@#',
	'#$#',
	'#.#',
	'##',
)

sok_trivial_v2 = (
	' #',
	'#.#',
	'#$#',
	'#@#',
	'##',
)

sok_trivial_s1 = (
	'#######',
	'#   ###',
	'#  $@.#',
	'# ### #',
	'#     #',
	'#######',
)

sok_trivial_s2 = (
	'#######_',
	'#--#--#_',
	'#-@$--##',
	'#--##--#',
	'##.----#',
	'_#######',
)

# 11 maps from 4x4s and 3 maps from 4x5s
sok_obvious_01 = (
	'__####',
	'__#@-#',
	'###--#',
	'#--*-#',
	'#--*-#',
	'######',
)

sok_obvious_02 = (
	'####__',
	'#-@###',
	'#-*--#',
	'#-*--#',
	'###--#',
	'__####',
)

sok_obvious_03 = (
	'__####',
	'__#-@#',
	'###--#',
	'#-*--#',
	'#---##',
	'#####_',
)

sok_obvious_04 = (
	'#####_',
	'#---##',
	'#*-*-#',
	'#@#--#',
	'#----#',
	'######',
)

sok_obvious_05 = (
	'######',
	'#----#',
	'#-$.-#',
	'##$.-#',
	'_#@-##',
	'_####_',
)

sok_obvious_06 = (
	'_#####',
	'_#.-.#',
	'###-$#',
	'#@-$-#',
	'#----#',
	'######',
)

sok_obvious_07 = (
	'######',
	'#.---#',
	'#--$-#',
	'#-#$##',
	'#.-@#_',
	'#####_',
)

sok_obvious_08 = (
	'#####_',
	'#---##',
	'#--$-#',
	'##$--#',
	'_#@..#',
	'_#####',
)

sok_obvious_09 = (
	'#####_',
	'#---##',
	'#..$-#',
	'#@$--#',
	'###--#',
	'__####',
)

sok_obvious_10 = (
	'######',
	'#----#',
	'#-#--#',
	'#@*$.#',
	'##---#',
	'_#####',
)

sok_obvious_11 = (
	'######',
	'#@*--#',
	'#-$-*#',
	'#-#--#',
	'#.---#',
	'######',
)

sok_obvious_12 = (
	'####__',
	'#-@#__',
	'#.-#__',
	'#--###',
	'#-$$-#',
	'#---.#',
	'######',
)

sok_obvious_13 = (
	'######_',
	'#-..@#_',
	'#--#$##',
	'#---$-#',
	'##----#',
	'_######',
)

sok_obvious_14 = (
	'_######',
	'_#@--.#',
	'##$#-##',
	'#-----#',
	'#-$-.-#',
	'#######',
)

sok_awkward_01 = (
	'choriban.5',
	' ######',
	' #  #.#',
	' #@ #.#',
	'##$   #',
	'#  $  #',
	'#   ###',
	'#####  ',
)

sok_awkward_02 = (
	'choriban.23',
	' ######',
	' #   .#',
	'## $  #',
	'#@$ # #',
	'# $ #.#',
	'###  .#',
	'  #####',
)

sok_awkward_03 = (
	'choriban.27',
	'####  ',
	'#  #  ',
	'#  ###',
	'#  $ #',
	'#  *.#',
	'#@*  #',
	'#  ###',
	'####  ',
)

sok_awkward_04 = (
	'choriban.30',
	'   ######',
	'####    #',
	'#@ $  $ #',
	'# # $# ##',
	'#...   # ',
	'######## ',
)

sok_awkward_05 = (
	'choriban.32',
	'#####  ',
	'#.. ###',
	'# .$  #',
	'## @$ #',
	' #  $ #',
	' ###  #',
	'   ####',
)

sok_awkward_06 = (
	'choriban.35',
	' #####',
	' #@..#',
	'##$*$#',
	'#    #',
	'#    #',
	'######',
)

sok_awkward_07 = (
	'choriban.37',
	'#####  ',
	'# ..###',
	'# . $ #',
	'#  #$ #',
	'#@$   #',
	'###   #',
	'  #####',
)

sok_awkward_08 = (
	'choriban.38',
	'#####  ',
	'#.. ###',
	'# .   #',
	'##  $ #',
	'#@$ $ #',
	'####  #',
	'   ####',
)

sok_awkward_09 = (
	'choriban.40',
	' ######',
	' # ...#',
	' #$#  #',
	'##  @ #',
	'# $$  #',
	'#    ##',
	'###### ',
)

sok_awkward_10 = (
	'choriban.41',
	'    ###',
	'  ###.#',
	'  #@ .#',
	'###$$.#',
	'#   $ #',
	'#    ##',
	'###### ',
)

sok_awkward_11 = (
	'choriban.42',
	'    ###',
	' ####+#',
	' #  ..#',
	'##$#  #',
	'#  $$ #',
	'#    ##',
	'###  # ',
	'  #### ',
)

sok_awkward_12 = (
	'choriban.43',
	'####### ',
	'#  ##@##',
	'#    $ #',
	'#   $..#',
	'#### #.#',
	'  #  $ #',
	'  #   ##',
	'  ##### ',
)

sok_awkward_13 = (
	'choriban.46',
	'  #### ',
	'###  # ',
	'#    ##',
	'# $ $ #',
	'#  #$@#',
	'#... ##',
	'###### ',
)

sok_awkward_14 = (
	'choriban.49',
	'  ######',
	'  #@ #.#',
	'####$ .#',
	'#  #  .#',
	'#  $ $ #',
	'#     ##',
	'#  #### ',
	'####    ',
)

sok_awkward_15 = (
	'choriban.52',
	'   #####',
	'####   #',
	'#  $   #',
	'#. @$$ #',
	'#..  ###',
	'######  ',
)

sok_awkward_16 = (
	'choriban.53',
	' ###   ',
	' #+#   ',
	' #*####',
	'##    #',
	'#  $# #',
	'# #   #',
	'# ### #',
	'#     #',
	'#######',
)

sok_awkward_17 = (
	'choriban.54 ',
	' ###      ',
	' #.#######',
	' #.#     #',
	'##+  ### #',
	'# * $### #',
	'# #  $   #',
	'#   $#####',
	'#    #    ',
	'######    ',
)

sok_awkward_18 = (
	'choriban.55',
	'    ###',
	' ####.#',
	' #  ..#',
	'## $ .#',
	'#@$$$##',
	'#    # ',
	'###### ',
)

sok_awkward_19 = (
	'simplified microban.8',
	'   ####',
	'  # ..@#',
	'  # $$ #',
	' ### ##',
	'#    ##',
	'# #   #',
	'#   # #',
	' ##   #',
	'   ###',
)

sok_awkward_20 = (
	'microban.16',
	' ####     ',
	' #  ####  ',
	' #     ## ',
	'## ##   # ',
	'#. .# @$##',
	'#   # $$ #',
	'#  .#    #',
	'##########',
)

sok_takaken_01 = (
	'scrambled egg',
	' #####',
	' # @ ###',
	'## #$  #',
	'# *. . #',
	'#  $$ ##',
	'### #.#',
	'  #   #',
	'  #####',
)

sok_takaken_02 = (
	'a point',
	'#####',
	'#   #####',
	'# # #   #',
	'# $   $ #',
	'#..#$#$##',
	'#.@$   #',
	'#..  ###',
	'######',
)

sok_takaken_03 = (
	'twins',
	' ######',
	'#   $. #  #####',
	'#.$    # #    .#',
	'#### .## #.  $ #',
	' ###  #  ###  ##',
	'  ##  #   ## $#',
	'   #  #    #. #',
	'####$#######$###',
	'#       @      #',
	'################',
)

sok_takaken_04 = (
	'rescue in the bay',
	'     ####',
	'   ###  ####',
	'#### $  #  #',
	'# $  $ $   #',
	'# # #$#$#  #',
	'# ....@.. ##',
	'###########',
)

sok_takaken_05 = (
	'baby classic',
	'#######',
	'#...  #',
	'# # $ #',
	'#  $  #',
	'###$ ##',
	'  # @#',
	'  ####',
)

sok_takaken_06 = (
	'key',
	'  #####',
	'###  @#',
	'#  $  #',
	'#    #########',
	'# #$   ....  #',
	'#  $ ######$ #',
	'##  ##    #  #',
	' ####     ####',
)

sok_takaken_07 = (
	'Love',
	'   #####',
	'  ## @ #',
	'  #    #  #####    ######',
	' ##   #####   ######    #',
	'##   ##  .#   #   #  ## #',
	'# . ## $#.## *$  ## ##  #',
	'#   ##  $  # .#  #     ##',
	'#   ###    ##   ## $$#. #',
	'#  $  #  ####   ####  . #',
	'# .$  ## #  ## ##  ## ###',
	'### #### #   # #    # #',
	'  # #  # #   # #    # #',
	'### #### ##### ###### ###',
	'#                       #',
	'#########################',
)

sok_takaken_08 = (
	'rule',
	'  ######',
	'###    ###',
	'#   $$ ..#',
	'# ##   # #',
	'#  ### @ #',
	'#    ##$ #',
	'# **  #  #',
	'### # # ##',
	' #  $ # #',
	' #  . #.#',
	' ###  ###',
	'   ####',
)

sok_takaken_09 = (
	'two points',
	' ######',
	' #    #',
	' #$  .#',
	'## ## #',
	'#     #',
	'# $ #.##',
	'###    #',
	'  ## @ #',
	'   #####',
)

sok_takaken_10 = (
	'in a mirror',
	' ########',
	' #  #   #',
	' #..#$$ #',
	' #  @   #',
	'##  #   ##',
	'#   #    #',
	'#...#$$$ #',
	'#   #    #',
	'##########',
)

sok_takaken_11 = (
	'two points again',
	' #####',
	' #   ######',
	'## # @    #',
	'# . . ### #',
	'#   #$ $  #',
	'###   #   #',
	'  #########',
)

sok_takaken_12 = (
	'magic box',
	'  #####',
	'### @ ###',
	'#   #   #',
	'#. ** $ #',
	'#   #   #',
	'#########',
)

sok_takaken_13 = (
	'short-sleeved shirt',
	'#########',
	'#  * *  #',
	'#  $ $  #',
	'### . ###',
	'  #$.$#',
	'  # . #',
	'  # . #',
	'  #@ ##',
	'  #####',
)

sok_takaken_14 = (
	'second UFO',
	'   #####',
	'   #   #',
	'   #   #',
	'####   #',
	'#  $$$ #',
	'#    # ##',
	'## ###  #',
	'#   ##  #',
	'#    #  #',
	'# ***...#',
	'###@ ####',
	'  ####',
)

sok_complex_01 = (
	'YASTGen #11 Chaos',
	'--#####',
	'###@ .#',
	'# $ #.#',
	'#  $$ #',
	'#.  # #',
	'#   $.#',
	'#######',
)

sok_complex_02 = (
	'Easy 3 Boxes #12',
	'#########',
	'#   #.  #',
	'#. .    #',
	'#  #$#@ #',
	'# $  ####',
	'####    #',
	'#    $  #',
	'#   #   #',
	'#########',
)

sok_complex_03 = (
	'MICROCOSMOS 02',
	'#################',
	'#  #  #  #  #   #',
	'#.$   #  #.$    #',
	'#  #.$ .$   #   #',
	'# @#  #  #  #   #',
	'#################',
)

optimal_solution_nums_strs = {
	sok_trivial_h1: '1/1',
	sok_trivial_h2: '1/1',
	sok_trivial_h3: '1/1',
	sok_trivial_h4: '2/1',
	sok_trivial_v1: '1/1',
	sok_trivial_v2: '1/1',
	sok_trivial_s1: ('12/2', '8/4'),
	sok_trivial_s2: ('23/3', '11/7'),
	sok_obvious_01: '17/4',
	sok_obvious_02: '18/4',
	sok_obvious_03: '19/4',
	sok_obvious_04: '24/6',
	sok_obvious_05: '28/4',
	sok_obvious_06: '30/8',
	sok_obvious_07: '32/8',
	sok_obvious_08: '33/9',
	sok_obvious_09: '35/7',
	sok_obvious_10: '42/7',
	sok_obvious_11: '43/7',
	sok_obvious_12: '39/11',
	sok_obvious_13: '45/10',
	sok_obvious_14: '64/12',
	sok_awkward_01: '46/15',
	sok_awkward_02: '91/25',
	sok_awkward_03: '62/18',
	sok_awkward_04: '87/24',
	sok_awkward_05: ('79/21', '71/23'),
	sok_awkward_06: '37/11',
	sok_awkward_07: '68/20',
	sok_awkward_08: ('82/22', '74/24'),
	sok_awkward_09: '48/18',
	sok_awkward_10: '47/16',
	sok_awkward_11: '83/21',
	sok_awkward_12: '115/43',
	sok_awkward_13: '80/23',
	sok_awkward_14: '81/28',
	sok_awkward_15: '61/23',
	sok_awkward_16: '52/10',
	sok_awkward_17: '127/30',
	sok_awkward_18: '54/18',
	sok_awkward_19: '79/20',
	sok_awkward_20: '100/39',
	sok_takaken_01: '170/43',
	sok_takaken_02: '185/42',
	sok_takaken_03: '144/47',
	sok_takaken_04: ('256/67', '250/69'),
	sok_takaken_05: '84/24',
	sok_takaken_06: ('180/52', '170/56'),
	sok_takaken_07: ('373/58', '369/60'),  # ('365/58', '361/60')
	sok_takaken_08: '185/41',
	sok_takaken_09: '93/16',
	sok_takaken_10: ('148/52', '146/54'),
	sok_takaken_11: '105/22',
	sok_takaken_12: '86/19',
	sok_takaken_13: ('213/54', '207/58'),
	sok_takaken_14: ('266/73', '247/75'),
	sok_complex_01: '144/38',
	sok_complex_02: '183/58',
	sok_complex_03: '211/82',
}

optimal_solution_nums_strs_by_type = {
	SOLUTION_TYPE_BY_SHIFTS: {k: v[0] if type(v) == tuple else v for k, v in optimal_solution_nums_strs.items()},
	SOLUTION_TYPE_BY_MOVES:  {k: v[1] if type(v) == tuple else v for k, v in optimal_solution_nums_strs.items()},
}

optimal_solution_strs = {
	sok_trivial_h1: 'R',
	sok_trivial_h2: 'L',
	sok_trivial_h3: 'R',
	sok_trivial_h4: 'lL',
	sok_trivial_v1: 'D',
	sok_trivial_v2: 'U',
	sok_trivial_s1: ('rddlllluurRR', 'LulldRRR'),
	sok_trivial_s2: ('ddrrruulLrrddllluluurDD', 'RRurDDrdLLL'),
	sok_obvious_01: 'rdddLUlldRurruulD',
	sok_obvious_02: 'lddRluurDrrddlUruL',
	sok_obvious_03: 'ldddlluRdrUruulDrdL',
	sok_obvious_04: 'drruruLullDRurDrddlUdllU',
	sok_obvious_05: 'ruuulldRurrddldlUrruulDulldR',
	sok_obvious_06: 'rdrruLuurDlddlluRdrUUruLdddrUU',
	sok_obvious_07: 'lluuurrrdLulldddrrUULulDDurrruLL',
	sok_obvious_08: 'ruruLulldRurDrddllURuulldRurDDurD',
	sok_obvious_09: 'uurrDrddlUruLullddRluurrdLrrddlUruL',
	sok_obvious_10: 'uurrrdddlUruulllddRRlluurrDullddrdrrULuurD',
	sok_obvious_11: 'dddrruuurDlddlluuuRldddrruuLulDDurrruLdddrU',
	sok_obvious_12: 'lddddrUUddrruLdlluurDuluurDDlddRRuLdlUU',
	sok_obvious_13: 'llddrdrruLLdlUluurrrDulllddrUluRddrdrruLLdlUU',
	sok_obvious_14: 'rrddllldRRuruullDurrddldlluRuurrddrdLLruuullddRdrUUdllldRRuluurR',
	sok_awkward_19: 'llDDDldddrruuLuuuurrdLulDDDlllddrrUdlluurRdddrruuLUUUluRdddlllddrrUdlluurRdrUUU',
	sok_awkward_20: 'lddrUdrruLLdlUUUruLLLulDDDldRuuurrrrdrDLdlUUruLLLulDDDlddrrULdlUruuurrrrddddrruLLdlUUUruLLLulDDDDldR',
	sok_complex_01: 'dDuurrddLLrrddLLUlluuRDRddrruuLLrruullDlldddRRuULrrruullDldRddlUruuurrddddLLuuRlddrruUUdlldlldRRuuulDrddlluRurrrddLLUluRRlddrruUllldldRRRluuullD',
	sok_complex_02: 'ullDDDrrddlULLdlluRRRRluuuulllddRRluurrdDDRddrruuLLdLUUUdlluurRRurrdLLLLrdddrddrUruLLdlLdlluRRRUUUdlluluurDrRRurrdLLLLrdddrrddlUruLdlUUUdllluuurrdLrRddllUdrruuRurrddlUruLdlllullDRddlU',
	sok_complex_03: 'uluurDrrddrUrrRRRuRRRurrdLulDlllddrUllllllluurDllllddrUluRRRdRRRRRRuRRRurDllllddrUluRRRurrdLLLLulDrdLLLdlUllluurDldRRRRRRdrUluRRRurrdLLLLulDrrrrrddlUruLLLLdLLLLLLdlUrrrrrrruulDrrrrddlUruLLLdLLLLLLuLLLrrrdrrruulD',
}

optimal_solution_strs_by_type = {
	SOLUTION_TYPE_BY_SHIFTS: {k: v[0] if type(v) == tuple else v for k, v in optimal_solution_strs.items()},
	SOLUTION_TYPE_BY_MOVES:  {k: v[1] if type(v) == tuple else v for k, v in optimal_solution_strs.items()},
}

verbose = False
def print_if_verbose(*args):
	if verbose:
		print(INFO_PREFIX, end='')
		print(*args)

def create_sokoban_map(lines):
	if lines[0][0].isalpha():
		lines = lines[1:]
	assert is_sokoban_map(lines), "Invalid Sokoban map:\n%s" % '\n'.join(lines)
	return numpy.array([list(line) for line in convert_and_pad_map_lines(lines)], dtype='<U1').T

def create_solver(sokoban_map_lines, reverse_barrel_mode=False, solution_alg=None, return_first=False):
	map = create_sokoban_map(sokoban_map_lines)
	descr = "Created %s solver for map" % (solution_alg or "default")
	return create_sokoban_solver(map, reverse_barrel_mode, solution_alg, return_first, descr if verbose else False)

def test_solution(sok, unique_solution_str=False, solution_alg=None, return_first=False):
	for solution_type in SOLUTION_TYPE_BY_SHIFTS, SOLUTION_TYPE_BY_MOVES:
		solver = create_solver(sok, False, solution_alg, return_first)
		solution_items = solver.solve(solution_type)
		test.not_none(solution_items)
		sok_id = sok[0] + ": " if sok[0][0].isalpha() else ''
		test.eq(sok_id + solver.last_solution_nums_str, sok_id + optimal_solution_nums_strs_by_type[solution_type][sok])
		if unique_solution_str:
			test.eq(solver.last_solution_str, optimal_solution_strs_by_type[solution_type][sok])
		else:
			test.ne(solver.last_solution_str, '')

def test_no_solution(sok):
	solver = create_solver(sok)
	solution_items = solver.solve()
	test.none(solution_items)
	test.none(solver.last_solution_nums_str)
	test.none(solver.last_solution_str)

def test_trivial_solutions():
	for sok in sok_trivial_h1, sok_trivial_h2, sok_trivial_h3, sok_trivial_h4, sok_trivial_v1, sok_trivial_v2, sok_trivial_s1, sok_trivial_s2:
		test_solution(sok, True)

def test_obvious_solutions():
	for sok in sok_obvious_01, sok_obvious_02, sok_obvious_03, sok_obvious_04, sok_obvious_05, sok_obvious_06, sok_obvious_07, sok_obvious_08, sok_obvious_09, sok_obvious_10, sok_obvious_11, sok_obvious_12, sok_obvious_13, sok_obvious_14:
		test_solution(sok, True)

def test_awkward_solutions():
	for sok in sok_awkward_01, sok_awkward_02, sok_awkward_03, sok_awkward_04, sok_awkward_05, sok_awkward_06, sok_awkward_07, sok_awkward_08, sok_awkward_09, sok_awkward_10, sok_awkward_11, sok_awkward_12, sok_awkward_13, sok_awkward_14, sok_awkward_15, sok_awkward_16, sok_awkward_17, sok_awkward_18, sok_awkward_19, sok_awkward_20:
		test_solution(sok, sok in (sok_awkward_19, sok_awkward_20), SOLUTION_ALG_ASTAR)

def test_takaken_solutions():
	for sok in sok_takaken_01, sok_takaken_05, sok_takaken_09, sok_takaken_11, sok_takaken_12:
		test_solution(sok)

def test_complex_solutions():
	for sok in sok_complex_01, sok_complex_02, sok_complex_03:
		test_solution(sok, False, SOLUTION_ALG_ASTAR, True)

def test_trivial_without_solutions():
	# already solved trivial map; unsolvable, since needs at least one shift
	test_no_solution((
		'#####',
		'#@* #',
		'#####',
	))
	# another circular unsolvable
	test_no_solution((
		'#####',
		'#@* #',
		'# * #',
		'#####',
	))
	# barrel on dead-barrel-cell
	test_no_solution((
		'#####',
		'#@$ #',
		'#  .#',
		'#####',
	))
	# deadlock
	test_no_solution((
		'#####',
		'#@$.#',
		'#.$ #',
		'#####',
	))

def test_algorithms_consistency():
	has_reverse_sol = [sok_obvious_03]
	for sok in sok_trivial_h3, sok_obvious_03, sok_obvious_06, sok_awkward_04, sok_awkward_16, sok_awkward_19:
		for reverse_barrel_mode in False, True:
			results = {}
			for alg in SOLUTION_ALG_DFS, SOLUTION_ALG_BFS, SOLUTION_ALG_UCS, SOLUTION_ALG_GREED, SOLUTION_ALG_ASTAR:
				# solve both types
				for typ in SOLUTION_TYPE_BY_SHIFTS, SOLUTION_TYPE_BY_MOVES:
					solver = create_solver(sok, reverse_barrel_mode, alg)
					sol = solver.solve(typ)
					exp_solution = not reverse_barrel_mode or sok in has_reverse_sol
					test.ok(sol or not exp_solution, "No expected %s solution %s for %s by %s" % (
						"reverse" if reverse_barrel_mode else "forward",
						optimal_solution_nums_strs_by_type[typ][sok], alg,
						"moves" if typ == SOLUTION_TYPE_BY_MOVES else "shifts"
					))
					results[alg, typ] = solver.last_solution_nums_str
				test.eq(results[alg, SOLUTION_TYPE_BY_MOVES], results[alg, SOLUTION_TYPE_BY_SHIFTS])
			def create_key(a, r, v):
				return ','.join([a, str(r), str(v)])
			# compare all results to BFS results
			for (alg, typ), v in results.items():
				test.eq(create_key(alg, reverse_barrel_mode, v), create_key(alg, reverse_barrel_mode, results[SOLUTION_ALG_BFS, typ]))

def test_prepare_solution_without_plates():
	sok = ('#######', '# @ $ #', '#######')
	solver = create_solver(sok)
	solver.prepare_solution()
	test.has_attr(grid, 'dead_barrel_bits')
	test.has_attr(solver, 'min_barrel_costs')
	test.has_attr(solver, 'min_char_barrel_costs')
	test.has_attr(solver, 'min_plate_barrel_costs')
	test.has_attr(solver, 'min_plate_char_barrel_costs')
	# ensure all floor cells are marked as dead without plates
	num_dead_barrel_bits = grid.dead_barrel_bits.count()
	test.gt(num_dead_barrel_bits, 0)
	test.eq(num_dead_barrel_bits, grid.num_bits)

def test_prepare_solution_with_plate():
	solver = create_solver(sok_obvious_10)
	solver.prepare_solution()
	dead_barrel_bits = grid.dead_barrel_bits
	test.gt(dead_barrel_bits.count(), 0)
	# now call with disable_prepare=True
	solver.disable_prepare = True
	solver.prepare_solution()
	# when disabled, dead_barrel_bits is no_bits
	test.eq(grid.dead_barrel_bits.count(), 0)
	# chech consistency
	solver.disable_prepare = False
	solver.prepare_solution()
	test.eq(grid.dead_barrel_bits, dead_barrel_bits)

def test_prepare_solution_char_filtering():
	solver = create_solver(sok_trivial_s2)
	# call prepare with char set vs char None and observe dead_barrel_bits differs or min_shifts differs
	solver.prepare_solution(None)
	all_dead_count = grid.dead_barrel_bits.count()
	# now restrict by char position: recompute
	solver.prepare_solution(solver.char_cell)
	char_dead_count = grid.dead_barrel_bits.count()
	# reachable plates only should reduce dead set (or stay equal) — expect char_dead_count <= all_dead_count
	test.le(char_dead_count, all_dead_count)

def test_superposition_idempotence():
	solver = create_solver(sok_trivial_h1)
	solver.prepare_solution(solver.char_cell)
	# create two barrel lists with same set but different order
	barrel_cells = tuple(solver.barrel_cells)
	grid.set_barrels(barrel_cells)
	sp1 = solver.find_or_create_super_position(solver.char_cell)
	grid.set_barrels(reversed(barrel_cells))
	sp2 = solver.find_or_create_super_position(solver.char_cell)
	test.eq(sp1, sp2)

def test_position_num_calculation():
	solver = create_solver(sok_trivial_h1)
	solver.prepare_solution(solver.char_cell)
	grid.set_barrels(solver.barrel_cells)
	char_idx = grid.to_idx(solver.char_cell)
	super_pos = solver.find_or_create_super_position(char_idx)
	root = Position(super_pos, char_idx, None, None, None)
	child = Position(super_pos, char_idx, root, (3, 2), [])
	test.eq(child.total_nums, (3, 2))
	# Reparent child with new own_nums
	child.reparent(root, (1, 1), [])
	test.eq(child.total_nums, (1, 1))

def test_find_solution_status_string():
	solver = create_solver(sok_trivial_h2)
	solver.unprocessed_positions = []
	solver.start_solution_time = time()
	status = solver.get_find_solution_status_str()
	test.is_in('positions', status)
	test.is_in('Finding', status)

args = sys.argv[1:]
verbose = args.count('-v') >= 2
if args.count('-v') >= 3:
	debug.configure([feature + ('+' * (args.count('-v') - 3)) for feature in ('solv', 'precosts')])
test = TestSuite("SokobanSolver", '-a' in args, '-v' in args, '-p' in args)
try:
	test_trivial_solutions()
	test_obvious_solutions()
	test_awkward_solutions()
	test_takaken_solutions()
	test_complex_solutions()
	test_trivial_without_solutions()
	test_algorithms_consistency()
	test_prepare_solution_without_plates()
	test_prepare_solution_with_plate()
	test_prepare_solution_char_filtering()
	test_superposition_idempotence()
	test_position_num_calculation()
	test_find_solution_status_string()
	test.finalize()
except KeyboardInterrupt:
	print()
	test.ok(False, "Tests terminated by user")
	test.finalize()
