#!/bin/bash

: ${SOKODUN=./sokodun}

time_params="-T 40"
quiet_params=" -q -q -q -q"

if test "$1" = "-t"; then
	time_params="$time_params -t"
	shift
fi

if test "$1" = "-v"; then
	quiet_params=""
	shift
fi

function solve_collection {
	ll_coll_id=$1
	name="$2"
	params="${@:3}"
	echo "[35m$name[m"
	echo "[2m$SOKODUN $time_params$quiet_params $params letslogic:$ll_coll_id[m"
	$SOKODUN $time_params$quiet_params $params letslogic:$ll_coll_id
}

solve_collection  6 "Microban 01 (92 of 155)" 1-92
solve_collection  8 "Original + Extra (6 of 90)" -1 1-3 7 38 78
solve_collection 12 "Microban 02 (65 of 135)" 1-65
#solve_collection 27 "Learning Sokoban (37)" -1
#solve_collection 28 "Serena 01 (100)" -1
solve_collection 29 "Mini Cosmos (40)"
solve_collection 29 "Mini Cosmos Reverse (31 of 40)" -r 4-34
solve_collection 30 "Micro Cosmos (40)"
solve_collection 31 "Nabo Cosmos (40)" -1
solve_collection 32 "Pico Cosmos (17 of 20)" -1 1-7 11-20
#solve_collection 35 "Simple Collection (61)"
solve_collection 37 "Anomaly 1 (30)" -1
solve_collection 38 "Anomaly 2 (30)" -1
solve_collection 39 "Novoban (50)" -A
solve_collection 40 "TBox 01 (48 of 50)" -1 1-48
solve_collection 41 "Loma (60)"
#solve_collection 42 "Sokoban2K (50)"
# all SokEvo levels are solvable, but some take up to 1:49 with -1
solve_collection 43 "SokEvo (80 of 107)" -1 1-80
#solve_collection 44 "SokHard (169)" -1
#solve_collection 45 "Sokodeal (100)" -1
#solve_collection 46 "MasterVIP (66)"
solve_collection 47 "Choriban (58 of 59)" -A 1-58
