#!/bin/sh

PATH=$PATH:`dirname $0`

if test "$1" = -r; then
	export CREATE_REDIRECT_PAGE=1
fi

if test "$1" = -R; then
	export ADD_REFRESH_TAG=1
fi

update-readme-md
create-html-elements-index
create-html-elements-news
create-html-elements-from-md sokobansolver
create-html-elements-authors
create-html-elements-puzzles
create-html-elements-videos
create-html-elements-screenshots
create-html-elements-themes

create-html-page index
create-html-page news
create-html-page download
create-html-page sokobansolver
create-html-page resources
create-html-page authors

for element_filename in elements/puzzles/*.html elements/videos/*.html elements/screenshots/*.html elements/themes/*.html elements/tutorials/*.html; do
	page_name=`echo $element_filename | cut -d/ -f2- | cut -d. -f1`
	create-html-page $page_name
done

# The optional script sync-html-pages-to-webserver if present may look like:
# rsync -av --copy-unsafe-links html/ "$HTML_ROOT"/
if /bin/which sync-html-pages-to-webserver >/dev/null 2>&1; then
	sync-html-pages-to-webserver
fi
