#!/usr/bin/python

import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + '/..')
from filetools import RegenerateFile
from screenshotinfo import get_main_screenshot_infos, get_css_class_for_screenshots

filename = "elements/index.html"
tmp_filename = filename + ".tmp"

if os.system("pandoc -o %s -f markdown -t html README.md" % tmp_filename) != 0:
	print("Failed to generate %s from README.md. Do you have pandoc" % tmp_filename)
	exit(1)

file = RegenerateFile(filename)
tmp_file = open(tmp_filename, "r")
if not tmp_file:
	print("Fatal error: No %s found, exiting" % tmp_filename)
	exit(1)

is_first = True
while line := tmp_file.readline():
	file.write(line)
	if is_first:
		infos = get_main_screenshot_infos()
		file.print('<div id="screenshots" class="%s">' % get_css_class_for_screenshots(infos))
		for info in infos:
			file.print('<a class="screenshot" href="%s"><img title="%s" src="%s"></a>' % \
				(info.html_filename, info.title, info.img_filename))
		file.print('</div>')
		is_first = False

file.finalize()
os.remove(tmp_filename)
