#!/bin/bash

export pagename=$1
if test -z "$pagename"; then
	echo "Usage: $0 NAME"
	exit 1
fi

assert_filename() {
	if ! test -f "$1"; then
		echo "Can't find file $1"
		exit 1
	fi
}

export page_uri="`echo \"$pagename.html\" | sed -s 's:\(^\|/\)index.html$:\1:'`"

export element_filename="elements/$pagename.html"
assert_filename $element_filename

export template_filename="elements/template$(echo "$CREATE_REDIRECT_PAGE" | sed 's/.\+/-redirect/').html"
assert_filename $template_filename

# set base= before running the script if no fully qualified base urls needed
: ${base=https://puzzle-dungeon.github.io/}

export category=`dirname "$pagename"`
if test "$category" = .; then
	export category=home
	: ${base=.}
else
	: ${base=..}
fi
export base

export refresh_tag=`echo "$ADD_REFRESH_TAG" | sed "s|.\+|\n<meta http-equiv=\"refresh\" content=\"0; url=$base$page_uri\">|"`

export sidebar_filename="elements/sidebars/$category.html"
assert_filename $sidebar_filename

output_filename="html/$pagename.html"

cat $template_filename | perl -pe '
	s/<{BASE}>/$ENV{base}/g;
	s/<{TITLE}>/$s = $ENV{pagename}; $s =~ s:(^|\/)index::; $s =~ s:\/: - :g; ucfirst($s || "home")/eg;
	s/<{SIDEBAR}>/`cat $ENV{sidebar_filename}`/e;
	s/<{CONTENT}>/`cat $ENV{element_filename}`/e;
	s/<{PAGEURI}>/$ENV{page_uri}/e;
	s/<{REFRESH}>/$ENV{refresh_tag}/e;
	s/<{(.*?) IF (\w+) (.*?)}>/$ENV{$2} eq $3 ? $1 : ""/eg;
' >$output_filename.new

if test -f "$output_filename" && test "`cat $output_filename`" = "`cat $output_filename.new`"; then
	rm -f $output_filename.new
	echo "File $output_filename was not changed"
else
	mv $output_filename.new $output_filename && \
	echo "Generated new $output_filename"
fi
